"""Initial migration

Revision ID: 1a40a332f2ba
Revises: 
Create Date: 2026-07-03 07:30:31.646058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a40a332f2ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('query', sa.Text(), nullable=False, comment="User's original query"),
    sa.Column('reasoning', sa.Text(), nullable=True, comment="Agent's reasoning over retrieved data"),
    sa.Column('chosen_action', sa.String(length=100), nullable=True, comment='Action the agent decided to take'),
    sa.Column('result', sa.Text(), nullable=True, comment='Output of the executed action'),
    sa.Column('explanation', sa.Text(), nullable=True, comment='Human-readable explanation of the decision'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False, comment='Origin format: json, csv, manual'),
    sa.Column('content', sa.Text(), nullable=False, comment='Full text content of the knowledge item'),
    sa.Column('content_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash for deduplication'),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Arbitrary metadata (category, price, specs, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_items')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
